#
# Copyright 2019-2021 The OpenZipkin Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

---
# permit depends_on/condition: service_healthy
version: "2.4"

services:
  kafka:
    image: ghcr.io/openzipkin/zipkin-kafka
    container_name: kafka
    ports:
      # Processes on the Docker host can set bootstrap server list to localhost:19092
      - 19092:19092
  kafka-topics:
    image: ghcr.io/openzipkin/zipkin-kafka
    container_name: kafka-topics
    entrypoint: "/bin/sh -c"
    command: "
      \"/kafka/bin/kafka-run-class.sh kafka.admin.TopicCommand --bootstrap-server kafka:9092 --create --topic zipkin-spans --partitions 2 --replication-factor 1 --if-not-exists
      &&
      /kafka/bin/kafka-run-class.sh kafka.admin.TopicCommand --bootstrap-server kafka:9092 --create --topic zipkin-trace --partitions 2 --replication-factor 1 --if-not-exists
      &&
      /kafka/bin/kafka-run-class.sh kafka.admin.TopicCommand --bootstrap-server kafka:9092 --create --topic zipkin-dependency --partitions 2 --replication-factor 1 --if-not-exists\"
      "
    depends_on:
      kafka:
        condition: service_healthy
  zipkin:
    image: beta.zipkin.io/openzipkin-contrib/zipkin-storage-kafka
    container_name: zipkin
    hostname: zipkin # required to route call to scatter-gather endpoint properly. should not be needed after #40 is solved
    ports:
      - 9411:9411
    environment:
      MODULE_OPTS: "-Dloader.path=storage-kafka -Dspring.profiles.active=storage-kafka-only-dependencies"
      STORAGE_TYPE: kafka
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_STORAGE_DIR: /zipkin/data
    volumes:
      - zipkin:/zipkin/data
    depends_on:
      kafka:
        condition: service_healthy
      kafka-topics:
        condition: service_started
volumes:
  zipkin:
